apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql-ns
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None  # Headless service so webapp can directly talk to the DB

